version: 2
updates:
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: daily
      timezone: Asia/Shanghai
    open-pull-requests-limit: 10
    rebase-strategy: disabled
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: daily
      timezone: Asia/Shanghai
    open-pull-requests-limit: 10
    rebase-strategy: disabled
